services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_nginx_app
    ports:
      - "8888:8888"   # HTTPS
      - "80:80"       # HTTP → редирект на HTTPS
    env_file:
      - .env
    volumes:
      - app_db:/app             # персистентность БД
    # environment:
    #   - DB_PATH=/app/app.db
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "--no-check-certificate",
    #          "https://localhost:8888/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 15s

volumes:
  app_db:
